Add include guards in `print.hpp`
The cmake build have the same file included twice with different paths:

```
/home/greg/github/enf/cdt/build_clang18_debug/bin/cdt-cpp -D_LIBCPP_BUILDING_LIBRARY -I/home/greg/github/enf/cdt/libraries/libc/cdt-musl/include -I/home/greg/github/enf/cdt/libraries/libc/cdt-musl/src/internal -I/home/greg/github/enf/cdt/libraries/libc/cdt-musl/src/crypt -I/home/greg/github/enf/cdt/libraries/libc/cdt-musl/arch/eos -I/home/greg/github/enf/cdt/libraries/libc++/cdt-libcxx/include -I/home/greg/github/enf/cdt/libraries -O3 -Wall -no-missing-ricardian-clause -g -g -std=gnu++17 -MD -MT eosiolib/CMakeFiles/eosio.dir/eosiolib.cpp.obj -MF eosiolib/CMakeFiles/eosio.dir/eosiolib.cpp.obj.d -o eosiolib/CMakeFiles/eosio.dir/eosiolib.cpp.obj -c /home/greg/github/enf/cdt/libraries/eosiolib/eosiolib.cpp
In file included from /home/greg/github/enf/cdt/libraries/eosiolib/eosiolib.cpp:3:
In file included from /home/greg/github/enf/cdt/libraries/eosiolib/contracts/eosio/system.hpp:9:
In file included from /home/greg/github/enf/cdt/libraries/eosiolib/contracts/eosio/../../core/eosio/name.hpp:9:
In file included from /home/greg/github/enf/cdt/libraries/eosiolib/core/eosio/reflect.hpp:3:
In file included from /home/greg/github/enf/cdt/build_clang18_debug/bin/../include/bluegrass/meta/refl.hpp:11:
/home/greg/github/enf/cdt/build_clang18_debug/bin/../include/eosiolib/core/eosio/print.hpp:78:16: error: redefinition of 'printhex'
   inline void printhex( const void* ptr, uint32_t size) {
               ^
/home/greg/github/enf/cdt/libraries/eosiolib/core/eosio/print.hpp:78:16: note: previous definition is here
   inline void printhex( const void* ptr, uint32_t size) {
               ^
```